name: Deploy to VPS

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deploys

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx (optional but useful for multi-arch builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Login to Docker Hub (requires secrets set up)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vkverma1122/docker-test:latest

      # 5. Deploy to VPS using SSH
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull vkverma1122/docker-test:latest
            docker stop docker-test || true
            docker rm docker-test || true
            docker run -d --name docker-test -p 3000:3000 vkverma1122/docker-test:latest
