name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # 3. Set up Docker Buildx (optional but useful for multi-arch builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 4. Login to Docker Hub (requires secrets set up)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push the Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./Dockerfile
          push: true
          tags: vkverma1122/docker-test:latest
          cache-from: type=registry,ref=vkverma1122/docker-test:latest
          cache-to: type=inline

      # 6. Deploy to VPS using SSH
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull vkverma1122/docker-test:latest
            docker stop docker-test || true
            docker rm docker-test || true
            docker run -d --restart unless-stopped --name docker-test -p 3000:3000 vkverma1122/docker-test:latest
            docker image prune -f
