name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # 3. Set up Docker Buildx (optional but useful for multi-arch builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 4. Login to Docker Hub (requires secrets set up)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push the Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: vkverma1122/docker-test:latest
          cache-from: type=registry,ref=vkverma1122/docker-test:latest
          cache-to: type=inline

      # 6. Copy docker-compose to VPS
      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "server/docker-compose.yml"
          target: "/opt/docker-test"
          strip_components: 1

      # 7. Deploy to VPS using SSH
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/docker-test
            docker-compose pull
            docker-compose up -d
            docker image prune -f
